name: final-project-d200
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.0
  - polars
  - pandas
  - seaborn
  - pre-commit
  - ipykernel
  - click
  - nbformat
  - pip
  - requests
  - pyarrow
  - statsmodels
  - pytorch
  - glum
  - joblib
  - skops
  - dalex
